/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Conversiones;

import  Conversiones.entrada;
import binario.Decimal;
import javax.swing.JOptionPane;

/**
 * Clase que representa la interfaz gráfica de usuario para realizar conversiones
 * de números decimales a otras bases numéricas.
 * 
 * <p>Permite ingresar un número en base decimal y convertirlo a distintas bases,
 * como binario, octal, hexadecimal, entre otras.</p>
 * 
 *
 * @author karla
 */

public class entrada extends javax.swing.JFrame {
    
    /**
     * Constructor de la clase entrada.
     * Inicializa los componentes de la interfaz.
     */
    public entrada() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIngresa = new javax.swing.JTextField();
        comboBases = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        combBas = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Conversión de bases:");

        txtIngresa.setBackground(new java.awt.Color(0, 0, 0));
        txtIngresa.setForeground(new java.awt.Color(255, 255, 255));
        txtIngresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresaActionPerformed(evt);
            }
        });

        comboBases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal" }));
        comboBases.setBorder(null);
        comboBases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBasesActionPerformed(evt);
            }
        });

        jLabel2.setText("=");
        jLabel2.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(10, 18));

        txtResultado.setBackground(new java.awt.Color(0, 0, 0));
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));

        combBas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binario", "Ternario", "Cuaternario", "Quinario", "Senario", "Septenario", "Octal", "Novenario", "Decimal", "Unidecimal", "Duodecimal", "Tridecimal", "Tetradecimal", "Pentadecimal", "Hexadecimal", "Vigesimal" }));
        combBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combBasActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIngresa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(combBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(comboBases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIngresa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresaActionPerformed
/**
     * Método ejecutado cuando el usuario pulsa el botón "Calcular".
     * Realiza la conversión del número ingresado en base decimal a la base seleccionada.
     * Muestra el resultado en el campo de texto correspondiente.
     * 
     * @param evt Evento de acción generado por el botón.
     */
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
     try {
    int numero = Integer.parseInt(txtIngresa.getText());

    if ("Decimal".equals(comboBases.getSelectedItem()) && "Ternario".equals(combBas.getSelectedItem())) {
        String resul = Decimal.DecimalATres(numero, 3);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Cuaternario".equals(combBas.getSelectedItem())) {
        
        String resul = Decimal.DecimalACuatro(numero, 4);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Quinario".equals(combBas.getSelectedItem())) {
        
        String resul = Decimal.DecimalACinco(numero, 5);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Senario".equals(combBas.getSelectedItem())) {
        
        String resul = Decimal.DecimalASeis(numero, 6);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Septenario".equals(combBas.getSelectedItem())) {
       
        String resul = Decimal.DecimalASiete(numero, 7);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Octal".equals(combBas.getSelectedItem())) {
       
        String resul = Decimal.DecimalAOctal(numero);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Novenario".equals(combBas.getSelectedItem())) {
        Decimal AT = new Decimal();
        String resul = AT.DecimalASiete(numero, 9);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Decimal".equals(combBas.getSelectedItem())) {
        Decimal AT = new Decimal();
        String resul = AT.DecimalASiete(numero, 10);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Binario".equals(combBas.getSelectedItem())) {
        String resul = Decimal.DecimalaBinario(numero);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Unidecimal".equals(combBas.getSelectedItem())) {
        String resul = Decimal.DecimalaUnidecimal(numero);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Duodecimal".equals(combBas.getSelectedItem())) {
        String resul = Decimal.DecimalaDuodecimal(numero);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Tridecimal".equals(combBas.getSelectedItem())) {
        String resul = Decimal.DecimalaTridecimal(numero);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Tetradecimal".equals(combBas.getSelectedItem())) {
        String resul = Decimal.DecimalaTetradecimal(numero);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Pentadecimal".equals(combBas.getSelectedItem())) {
        String resul = Decimal.DecimalaPentadecimal(numero);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Hexadecimal".equals(combBas.getSelectedItem())) {
        String resul = Decimal.DecimalaHexadecimal(numero);
        txtResultado.setText(resul);
    }
    if ("Decimal".equals(comboBases.getSelectedItem()) && "Vigesimal".equals(combBas.getSelectedItem())) {
        String resul = Decimal.DecimalaVigesimal(numero);
        txtResultado.setText(resul);
    }

} catch (NumberFormatException e) {
    // Si el texto no es un número válido, muestra un mensaje de error
    JOptionPane.showMessageDialog(null, "Por favor, ingresa solo números enteros.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
    txtIngresa.setText(""); // limpia el campo si quieres
    txtResultado.setText(""); // también limpia el resultado
}

         
           
       
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void combBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combBasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combBasActionPerformed

    private void comboBasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBasesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboBasesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtIngresa.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> combBas;
    private javax.swing.JComboBox<String> comboBases;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtIngresa;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
